DATA_TYPES = {
    'AutoField':         'int IDENTITY (1, 1)',
    'BooleanField':      'bit',
    'CharField':         'nvarchar(%(max_length)s)',
    'CommaSeparatedIntegerField': 'nvarchar(%(max_length)s)',
    'DateField':         'datetime',
    'DateTimeField':     'datetime',
    'DecimalField':      'numeric(%(max_digits)s, %(decimal_places)s)',
    'FileField':         'nvarchar(%(max_length)s)',
    'FilePathField':     'nvarchar(%(max_length)s)',
    'FloatField':        'double precision',
    'IntegerField':      'int',
    'IPAddressField':    'nvarchar(15)',
    'NullBooleanField':  'bit',
    'OneToOneField':     'int',
    'PhoneNumberField':  'nvarchar(20)',
    'PositiveIntegerField': 'int CONSTRAINT [CK_int_pos_%(column)s] CHECK ([%(column)s] > 0)',
    'PositiveSmallIntegerField': 'smallint CONSTRAINT [CK_smallint_pos_%(column)s] CHECK ([%(column)s] > 0)',
    'SlugField':         'nvarchar(%(max_length)s)',
    'SmallIntegerField': 'smallint',
    'TextField':         'nvarchar(max)',
    'TimeField':         'datetime',
    'USStateField':      'nchar(2)',
}
